language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: z7ePjdTTQ6TRmhWxDoYstmrqNf3STCiXgfbhN5lZ0sFQkSidhVulkHnaXVlNVeppttfnu3N6T0w6XRj9aey/4lBP26au/gEEit3Ps+CorOg276+2PxFEqaUZ0o3UMiL3fIjSZpWwLqtIn9bAANGrRzteA3/2n986161eapInsteSHoTo2CN2P+SpDbB2DHFEqnGBnRAI0dDGep7/0RqeZ8IwvYZbH2/OuuRh25PF/5WpWzoWPL/cqzPUSYOC/SOX1YDVJguQ57o3S6eoZngTF8Z9FUfK3rqDj4EcA+Q8zt7lTLDJ4r3eBRSP6jJNodWDdETWQoow+oSEpMZMhpUi9/UCulTrLYfX30gs/tPmecueTOfGsuoR+qM1vzHV6kNBrg6ASadED35LIEyGYnQMAX4BaSibSkuG5qo/zxiAEUUsml1qocqwR+dwYQj7/nfTWdrLGQZqRVl/QyjaT4G1NihziWpqMXVim3H/BX9rf1vxAvk3JEZJe3SlUvvbslSzzh8KFnhjewPAiI4EMXHZd/iY13v0H9OuvD0wvRWHo9f3kc8Ane3wY174Ncrid757YvfXqS4FEjl+IPUvEHu8DvSo+bqOHJIfI5PubZPAx9+r5U+9w3mj5lbfdPgABgOVyBH3nfVq47SWFoYeqoU4k+FgDnLsyozS1NzYd4MZNtQ=
  app: radiant-springs-71930
  on:
    repo: kdxcii/hotandcoldwithtest
